#$(error Choose suitable values for the variables below, then delete this line.)

# The name of the main header file for the library
FILENAME=/usr/include/zip.h

# A regular expression that matches functions that should be exported
REGEX=zip_.*

# Linker flags
LIBRARY=-lzip

# Extra flags for the C compiler
CFLAGS=
